### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by JVariance** [HermanLederer/mp3-tag-assistant#1] opened 2022-07-22 18:18 UTC
Metashine 3.0.0-rc.1 (Pre-release):

On startup I get the following error:

```javascript
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
...tmp.node is not a valid win32 application.
trnp.node at process.func [as dlopen]
...
```

**Comment by StarLederer** [comment] 2022-08-06 14:17
Before I address the issue.. OMG I GOT AN ISSUE!!! I am so happy that someone wants to use my app! ♡

And as to the issue: It seems like i completely missed the fact that one of the modules that is written in rust needs to be compiled for different platforms (Windows in your case). I will try to fix that tomorrow.

As a temporary workaround you can use a version of Metashine before 3.0.0 or open it in a Linux VM.

**Comment by StarLederer** [comment] 2022-08-08 11:02
I updated the release please try installing it again. The new installer can be fund in [the same release](https://github.com/HermanLederer/metashine/releases/tag/v3.0.0-rc.1) since no code has been changed, just built properly. I was unable to validate it since I am getting a bad exe format error in Wine, ~but I found material suggesting that it is possibly a Wine error~. Please try the new installer and let me know if it worked because i have no other way of finding out

**Comment by JVariance** [comment] 2022-08-16 11:16
I'm a bit late, sry 😃 
I downloaded the exe and installed Metashine again, but I still get the same error.

**Comment by StarLederer** [comment] 2022-08-16 11:54
Well that sucks... ~I suspect i might need a windows device to build a windows version~. I will look into AppVeryor CD. Will also set up a Mac version while at it.

If you would like to help you could try building from source and tell me if it works for you that way. This will confirm that something is wrong with the build step and not in the code.

If you want to build from source:

- Clone the repository
- Open the directory in a terminal
- Execute `pnpm install`
- Execute `pnpm run build`
- Execute `pnpm run compile` or `pnpm exec electron-builder -w`
- The installer will be found in the dist folder

To build from source you will need the folloiwng tools:

- Node.js ~= 16.13
- Pnpm ~= 7.9.0
- Rust ~= 1.62

**Comment by JVariance** [comment] 2022-10-09 11:33
I tried to build, but I get the following error:
```powershell
X [ERROR] Could not resolve "../dist/index.node"

    node_modules/.pnpm/file+packages+native-addon/node_modules/@metashine/native-addon/lib/index.js:1:14:
      1 │ export * from '../dist/index.node';
        ╵               ~~~~~~~~~~~~~~~~~~~~
```

**Comment by StarLederer** [comment] 2022-10-10 10:45
That's strange. This means that the native-addon package failed to build. Assuming that, the build process should have failed sooner. To investigate further you can `cd` into `packages/native-addon` and try running `pnpm run build` or `pnpm run build-release` and see if that creates `packages/native-addon/dist/index.node` successfully

**Comment by JVariance** [comment] 2022-10-10 15:27
Yes, both commands work.
But still the same error afterwards when following the initial procedure.

**Comment by StarLederer** [comment] 2022-10-16 16:35
> I tried to build, but I get the following error:

Fixed this part. Since native-addon is a binary dependency it needs to be relinked to take effect (`pnpm i` before `pnpm run build:electron`). I made the necessary modification to the build script.

Please retry following the original instructions

**Comment by JVariance** [comment] 2022-10-17 14:54
Build and compilation work!
But on startup I now get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'axios'
Require stack:
at Module._resolveFilename (node:internal/modules/cjs/loader:934: 1 5)
at Function.n._resolveFilename
at Module._load (node:internal/modules/cjs/loader:779:27)
at Function.c._load
at Module.require (node:internal/modules/cjs/loader: lü:19)
at require 18)
at (C:\Program
Files\M etash ndclo u d. I .js:39: 1 5)
at Module._compile (node:internal/modules/cjs/loader:1110: 14)
at Object.Module._extensions.js (node:internal/modules/cjs/loader: 1140:10)
at Module.load
```

**Comment by StarLederer** [comment] 2022-11-01 20:51
Big news! Just managed to cross-compile native-addon for windows and got it to load in Wine! 🎉

I think [neon](https://neon-bindings.com/) was copying the wrong build artifact (since i was able to reproduce the error by manually copying the wrong build artifact 😅). I will probably open an issue about this on the Neon GitHub page.

There is once again hope for being able to build for windows on my machine.

**Comment by StarLederer** [comment] 2022-11-01 21:07
> on startup I now get the following error...

Electron builder [explicitly states](https://www.electron.build/index.html#note-for-pnpm) that there are some pnpm config modifications that need to be made but these modifications remove all pnpm benefits over npm so I worked around its issues a different way. Seems like it only works on my machines though...

I will create a branch with their workaround applied and ask you to test it out. If it works I will convert the project to npm

**Comment by JVariance** [comment] 2022-11-02 13:42
I can't wait 🤠

**Comment by StarLederer** [comment] 2022-11-02 16:22
Managed to build the app and reach the same issue with node modules not loading.

Closing because the native-addon issue seems to have been solved.

Node modules not loading is unrelated and should be discussed in #3. Thank you for your help so far ☺️

**Closed as completed by StarLederer** 2022-11-02 16:22 UTC
